name: Gatsby Publish

on:
  pull_request:
    branches:
      - deploy
    types: [closed]

jobs:
  gh-pages-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set-up"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: "Install"
        run: npm install
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}