name: Gatsby Publish

# on:
#   push:
#     branches:
#       - main

on: [push]

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: "Github Pages Deployment"
        run: |
          npm install
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -u "github-actions-bot <support+actions@github.com>"
        # if: ${{ github.ref == 'refs/heads/master' }} # only deploy master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}