name: Main Pipeline

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize, reopened, closed]

jobs:

  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run serve

  gh-pages-deploy:
    if: ${{ github.event.pull_request.merged }}
    needs: run-e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Set-up"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: "Install"
        run: npm install
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}